CARGO := cargo

all: docs

docs: docs/**.md
	rm -f README.md
	echo "<!-- This file is autogenerated by 'make docs'. Do not edit! -->" > README.md
	make docs-index
	make docs-architecture

docs-index:
	cat docs/index.md >> README.md

docs-architecture:
	cat docs/general/architecture.md >> README.md