name: Spellchecker

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Spellcheck Documentation
      uses: rojopolis/spellcheck-github-actions@0.28.0
      with:
        config_path: .github/workflows/spellcheck/spellcheck.yml
        source_files: README.md
        task_name: README
