---
# tasks file for revproxytunnel
- name: Create temporary directory for Dockerfile
  ansible.builtin.tempfile:
    state: directory
  register: dockerfile_dir

- name: Template the Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ dockerfile_dir.path }}/Dockerfile"
    # TODO Minimise permissions
    mode: "644"

- name: Template the Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ dockerfile_dir.path }}/Caddyfile"
    # TODO Minimise permissions
    mode: "644"

- name: Build Image
  community.docker.docker_image:
    name: "{{ revproxytunnel_build_image_name }}"
    tag: "{{ revproxytunnel_build_image_tag }}"
    source: build
    build:
      path: "{{ dockerfile_dir.path }}"
      dockerfile: "Dockerfile"
    state: present
