---

- name: Install Podman
  become: true
  update_cache: true
  ansible.builtin.apt:
    package:
      - podman

- name: Remove existing quadlet definitions
  ignore_error: true
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: absent
    recurse: true

- name: Update quadlet definitions
  loop: "{{ lookup('fileglob', './templates/*.j2') }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/contaienrs/systemd/{{ item | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode : '0644'


#- name: Update containers

#- name: Update container components

- name: Reload Quadlets
  ansible.builtin.systemd_service:
    daemon_reload: true

#- name: Ensure container services

# TODO set up backup service