---
# Ansible role for setting up the freyground virtual network.

- name: Ensure port forwarding rules

- name: Install VNet Packages
  become: true
  ansible.builtin.apt:
    package:
      - certbot
      - strongswan
      - strongswan-pki
      - strongswan-swanctl
      - libcharon-extra-plugins
    update_cache: true
  when: "'vnet_hcloud' in group_names or 'vnet_azcloud' in group_names"

- name: Install IPSec config (AZCLOUD)
  become: true

- name: Install IPSec config (HCLOUD)
  become: true

- name: Install PSK
  become: true