const fs = require("fs").promises;
var md = require("markdown-it")()
  .use(require("markdown-it-include"))
  .use(require("markdown-it-textual-uml"));
// Allocate buffer for intermediate values
var data;
fs.readFile("docs/index.md").then(async (data) => {
  out = md.render(data.toString());
  out = "<!--This file is autogenerated. Do not Edit! -->\n" + out;

  await fs.writeFile("README.md", out);
});
