FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 80
EXPOSE 443
EXPOSE 51820

COPY Caddyfile /etc/caddy/Caddyfile
COPY wg0.conf /etc/wireguard/wg0.conf

RUN apt update && apt install wireguard caddy -y; rm -rf /etc/apt/cache
